baseurl: '/'
permalink: pretty
title: 'Cambridge AI Builder Club'

logo:
  mobile: "images/logo/cam-ai-builder-logo-mobile.png"
  mobile_height: "auto"
  mobile_width: "32px"
  desktop: "images/logo/cam-ai-builder-logo.png"
  desktop_height: "auto"
  desktop_width: "130px"

home: 
  limit_services: 6

collections:
  events:
    output: true
    sort_by: weight
  blogs:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
